### ISSUE TITLE
如何跑起来

### ISSUE THREAD

**Issue by shanyipeng** [AlphaYu/Adnc#1]
如何安装 里面配置文件如何配置 ，

**Comment by AlphaYu** [comment]
ClientApp 是前端代码
Vue写的，需要安装npm依赖包，步骤如下。
# Install dependencies 
npm install --registry=https://registry.npm.taobao.org
# Serve with hot reload at localhost:5001
npm run dev

ServerApi（.net core 3.1） 是后端项目你要安装redis,mysql,mongodb,skywalking(这个可选),修改appsettings.development.json与nlog.config。数据库脚本在doc目录里面。

webapi是启动项目。Adnc.Gateway ，Adnc.Maintaining调试调试环境可以不跑，这两个项目是独立的。

**Comment by shanyipeng** [comment]
consul 在项目中如何使用的

**Comment by AlphaYu** [comment]
首先你需要自己部署consul集群。
 consul 两大功能
（一）配置中心，
1\配置webpai项目 appsettings.development.json  文件的 Consul节点，里面有详细注释。
2\ 在webpai项目 Program.cs 文件中读取配置中心配置
   //从consul配置中心读取配置
    var consulOption = configuration.GetSection("Consul").Get<ConsulOption>();
     cb.AddConsul(new[] { consulOption.ConsulUrl }, consulOption.ConsulKeyPath);
 (二)服务注册/发现
1、配置webpai项目 appsettings.development.json  文件的 Consul节点，里面有详细注释。
2、webapi项目的startup.cs Configure方法中的最后一行，表示注册服务到cosnul
 app.RegisterToConsul(Configuration.GetSection("Consul").Get<ConsulOption>());
3\发现
var address = await ServiceConsumer.GetServicesAsync("consul地址", "服务名称");

**Comment by shanyipeng** [comment]
![image](https://user-images.githubusercontent.com/16831356/89848328-af50e080-dbb8-11ea-8621-d6bb574563c3.png)

**Comment by shanyipeng** [comment]
能否留下QQ 一起沟通一下

**Comment by AlphaYu** [comment]
你项目的启动地址是http://localhost:5000,你把启动地址设置成http://你的ip:5000。就可以了。
你加下QQ群：780634162
