### ISSUE TITLE
请问怎么实现事务？

### ISSUE THREAD

**Issue by CGuoL** [AlphaYu/Adnc#13]
rt，项目中有可以学习事务的地方吗？

**Comment by AlphaYu** [comment]
参考wiki里，仓储使用的文章，有详细介绍。

**Comment by AlphaYu** [comment]
https://github.com/AlphaYu/Adnc/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E4%BB%93%E5%82%A8(%E4%BA%8C)-%E5%B7%A5%E4%BD%9C%E5%8D%95%E5%85%83

**Comment by CGuoL** [comment]
> 参考wiki里，仓储使用的文章，有详细介绍。

sorry，用的手机，没看见wiki。
