### ISSUE TITLE
新增部门之后随即返回列表没有出现新增的项（缓存问题）

### ISSUE THREAD

**Issue by kuiningcomeon** [AlphaYu/Adnc#15]
新增部门之后随即返回列表没有出现新增的项，刷新也无，只有再次编辑下某一个部门，才会出现，编辑和删除也存在类似的缓存不同步问题，希望可以改善一下。

**Comment by AlphaYu** [comment]
刚测试了下，0.8.1版本确实存在这个bug。
我会尽快修复。应该是拦截器执行异步方法的问题。谢谢。

**Comment by AlphaYu** [comment]
已经修复

**Comment by kuiningcomeon** [comment]
> 已经修复

好的，操作过是可以的了。
