### ISSUE TITLE
你们为何不考虑用MassTransit

### ISSUE THREAD

**Issue by tonyqus** [AlphaYu/Adnc#17]
我最近在围观国内.net圈的使用习惯，我发觉一个非常奇怪的现象，大家好像只知道CAP，不知道MassTransit。

能说一下CAP有什么独到的地方吗？还是说你们其实不知道MassTransit?

**Comment by AlphaYu** [comment]
MassTransit 知道的，也看过。目前选择CAP来处理分布式事物，1.CAP的demo更容易看懂，文档中英文都有，上手无难度，这一点是自身英文水平低的原因，。2.CAP提供了Dashboard,在Dashboard上可以人工介入处理失败的任务。

**Comment by AlphaYu** [comment]
当然CAP也有一些吐槽点。MassTransit 后期有时间我也会静心研究下。

**Comment by tonyqus** [comment]
这样啊，那我知道了，看来缺个人翻译MassTransit的文档
