### ISSUE TITLE
下一个版本Net 6，ORM能不能用freesql

### ISSUE THREAD

**Issue by mx4g** [AlphaYu/Adnc#18]
下一个版本Net6 ，ORM 能不能 选择用freesql？

**Comment by mx4g** [comment]
freesql 这个很强大，速度接近Dapper，而且中文文档写得很详细，一看就懂！

**Comment by AlphaYu** [comment]
下个大版本不打算集成freesql，目前adnc如果是纯
sql直接走dapper,其他操作走efcore。同一套仓储接口，用多种orm实现很难。心力不够啊！
