### ISSUE TITLE
内网IP错误

### ISSUE THREAD

**Issue by q5401103q** [AlphaYu/Adnc#19]
位于 Microsoft.AspNetCore.Authorization.CapDashboardAuthorizationFilter  的 AuthorizeAsync 方法
···
public class CapDashboardAuthorizationFilter : IDashboardAuthorizationFilter
{
    public async Task<bool> AuthorizeAsync(DashboardContext context)
    {
        //这里定义capdashboard外网验证，需要完善
        //默认内网可以访问
        if (context.Request.LocalIpAddress == "127.0.0.0.1")
        {
            return await Task.FromResult(true);
        }
        return await Task.FromResult(true);
    }
}
···
以上的127.0.0.0.1 应当为127.0.0.1 ?

**Comment by AlphaYu** [comment]
收到，谢谢。应该是127.0. 0.1

**Comment by AlphaYu** [comment]
收到，谢谢。应该是127.0. 0.1
