### ISSUE TITLE
可否写一个Windows部署的教程？

### ISSUE THREAD

**Issue by dmhai** [AlphaYu/Adnc#25]
现有的教程是Linux的，但是公司资源不是我能控制的，我们必须要在Windows系统使用。

花了不少时间，尝试把教程改成Windows部署的，但由于之前没怎么接触容器和微服务，遇到不少问题。

比如Windows下 把容器ip赋值到变量，在容器内部读取不到，比如时间同步之类的，比如各种容器ip内网ip外网ip，看的有点晕。

希望能出一篇 Windows部署的具体教程。感谢~

感谢~

**Comment by AlphaYu** [comment]
即便是linux环境下《如何手动部署》也只是一个演示教程，并不适合实际的生产环境。
实际生产环境如何灵活部署，主要在于你需要加深对consul、docker、gateway等相关概念理解。
windows环境下如何部署，我也没有经验，抱歉。

**Comment by dmhai** [comment]
好吧，本来还想着和普通单体应用一样，找个能直接部署的，然后一边改着用一边学，看来是我想的太简单了，

这个 issues 可以关了，感谢回复。
