### ISSUE TITLE
连接MySQL的使用过程中，DBContext出现线程不安全

### ISSUE THREAD

**Issue by nick-yegw** [AlphaYu/Adnc#32]
当前，在使用比较旧的版本下，遇到了下面的问题：
![image](https://user-images.githubusercontent.com/2286029/164499159-160d72c7-4edd-4c35-b81d-a7527d6fa949.png)

调用的方法如下：

![origin_img_v2_07d21a94-493e-4ef0-9545-40a489e1156g](https://user-images.githubusercontent.com/2286029/164499551-cb2153e2-b092-4728-b803-c2b90a7504ae.jpg)

想请教一下，如何去解决这些问题？

**Comment by nick-yegw** [comment]
DBContext的配置如下：

![image](https://user-images.githubusercontent.com/2286029/164500293-3f8b94e7-58c3-483a-a5d0-912742152a5e.png)

**Comment by nick-yegw** [comment]
具体是下面的这一行，需要加上await， 对么？

```c#
return ExecuteAsync<TSource, Task<TSource>>(QueryableMethods.FirstOrDefaultWithoutPredicate, source, cancellationToken);
```

**Comment by AlphaYu** [comment]
不要改基础方法，基础方法无问题的。你要修改你出问题的地方。关于连接池，如果是mysql连接池在连接串中配置就行。如果是dbcontext连接池，除非性能要求极致，否则配置意义不大，你可以自己查看相关资料如何配置。

**Comment by AlphaYu** [comment]
不要改基础方法，基础方法无问题的。你要修改你出问题的地方。关于连接池，如果是mysql连接池在连接串中配置就行。如果是dbcontext连接池，除非性能要求极致，否则配置意义不大，你可以自己查看相关资料如何配置。
