### ISSUE TITLE
寻求有缘人帮忙做一个简洁、漂亮的登录页面，目前这个太low了。

### ISSUE THREAD

**Issue by AlphaYu** [AlphaYu/Adnc#35]
https://github.com/AlphaYu/Adnc/blob/master/src/ClientApp/src/views/login/index.vue

**Comment by zy-zero** [comment]
![image](https://user-images.githubusercontent.com/23359848/169256472-f8269f8f-8c02-450a-ba29-a4595d047736.png)
不知可否？

**Comment by zy-zero** [comment]
![image](https://user-images.githubusercontent.com/23359848/169256611-6d4f59b5-9c34-4106-b3be-5699372e54bd.png)
这是没有autofull的时候

**Comment by AlphaYu** [comment]
谢谢。比现在的高级，背景图片有合适的吗？

**Comment by zy-zero** [comment]
木有，我只会改改样式，画图不会，抱歉


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月19日 18:23:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AlphaYu/Adnc] 寻求有缘人帮忙做一个简洁、漂亮的登录页面，目前这个太low了。 (Issue #35)




 
谢谢。比现在的高级，背景图片有合适的吗？

**Comment by AlphaYu** [comment]
你提交下，先chekcout dev分支。

**Comment by AjuPrince** [comment]
有缘人，将首页、logo 整体设计下。

**Comment by zy-zero** [comment]
> 你提交下，先chekcout dev分支。

remote: Permission to AlphaYu/Adnc.git denied to zy-zero.
fatal: unable to access 'https://github.com/AlphaYu/Adnc.git/': The requested URL returned error: 403
我似乎没有权限

**Comment by zy-zero** [comment]
![image](https://user-images.githubusercontent.com/23359848/169433785-0838400c-8ac0-4162-8a07-740f5b2b2fa9.png)
背景可改为纯色

**Comment by AlphaYu** [comment]
添加你了为合作者了，记得先切换到 dev分支,在dev分支里面修改，然后再提交上来。

**Comment by zy-zero** [comment]
dev 已提交

**Comment by AlphaYu** [comment]
看到了，谢谢。
