### ISSUE TITLE
DefaultBinarySerializer

### ISSUE THREAD

**Issue by HeLinSpace** [AlphaYu/Adnc#60]
DefaultBinarySerializer  .net 6中 好像不能用这个了  BinaryFormatter

https://docs.microsoft.com/zh-cn/dotnet/standard/serialization/binaryformatter-security-guide

**Comment by AlphaYu** [comment]
从.NET5开始就不推荐用了，说是安全问题。你可以设置默认用json序列化即可。
[DefaultJsonSerializer.cs](https://github.com/AlphaYu/Adnc/blob/master/src/ServerApi/Infrastructures/Adnc.Infra.Caching/Core/Serialization/DefaultJsonSerializer.cs)

```json
  "Redis": {
     //other nodes
    "Provider": "StackExchange",
    "SerializerName": "json",
    //other nodes
  }
```

**Comment by HeLinSpace** [comment]
> 从.NET5开始就不推荐用了，说是安全问题。你可以设置默认用json序列化即可。 [DefaultJsonSerializer.cs](https://github.com/AlphaYu/Adnc/blob/master/src/ServerApi/Infrastructures/Adnc.Infra.Caching/Core/Serialization/DefaultJsonSerializer.cs)
> 
> ```json
>   "Redis": {
>      //other nodes
>     "Provider": "StackExchange",
>     "SerializerName": "json",
>     //other nodes
>   }
> ```

嗯呢，已使用json，我只是提醒一下大佬哈
