### ISSUE TITLE
按照readme启动，无法登录，更改webapi端口为5002后正常

### ISSUE THREAD

**Issue by JaneConan** [AlphaYu/Adnc#69]
![image](https://user-images.githubusercontent.com/26090153/193446252-fb9b6e26-c8c4-40a6-92ee-c55f14744594.png)

![image](https://user-images.githubusercontent.com/26090153/193446289-7655a9dc-2258-4be0-aad3-69b63ae8b4f7.png)

**Comment by AlphaYu** [comment]
5002是开发环境的网关端口，和这里没有关系。
前端连接的是5002端口，所以你要启动网关。

**Comment by JaneConan** [comment]
所以，正确的启动顺序是什么

1、启动webapi
2、启动网关
3、启动前台

**Comment by AlphaYu** [comment]
> 所以，正确的启动顺序是什么
> 
> 1、启动webapi 2、启动网关 3、启动前台

看 https://aspdotnetcore.net/docs/quickstart/
