### ISSUE TITLE
按照官方文档启动后，gateway。启动后会链接到 10.0.8.15:8500,我还需要部署什么吗？

### ISSUE THREAD

**Issue by xuguilins** [AlphaYu/Adnc#75]
当前环境：  macOs
ide: Rider

geteway启动后出现 
ystem.Net.Http.HttpRequestException: Operation timed out (10.0.8.15:8500)
 ---> System.Net.Sockets.SocketException (60): Operation timed out

**Comment by AlphaYu** [comment]
development环境不应该连接consul的啊
