### ISSUE TITLE
mac 系统的 visual studio 2022 打开工程的时候报错，怎么解决

### ISSUE THREAD

**Issue by dragonwtl** [AlphaYu/adnc#87]
无法加载解决方案: /Users/tielingwang/Documents/dotnet/demoproject/adnc-master/src/ServerApi/Adnc.sln
Load operation failed.
尝试加载项目“/Users/tielingwang/Documents/dotnet/demoproject/adnc-master/src/ServerApi/Demo/Usr/Adnc.Demo.Usr.Api/Adnc.Demo.Usr.Api.csproj”时出错: Invalid value for Link property
尝试加载项目“/Users/tielingwang/Documents/dotnet/demoproject/adnc-master/src/ServerApi/Demo/Maint/Adnc.Demo.Maint.Api/Adnc.Demo.Maint.Api.csproj”时出错: Invalid value for Link property
尝试加载项目“/Users/tielingwang/Documents/dotnet/demoproject/adnc-master/src/ServerApi/Demo/Ord/Adnc.Demo.Ord.Api/Adnc.Demo.Ord.Api.csproj”时出错: Invalid value for Link property
尝试加载项目“/Users/tielingwang/Documents/dotnet/demoproject/adnc-master/src/ServerApi/Demo/Whse/Adnc.Demo.Whse.Api/Adnc.Demo.Whse.Api.csproj”时出错: Invalid value for Link property
尝试加载项目“/Users/tielingwang/Documents/dotnet/demoproject/adnc-master/src/ServerApi/Demo/Cust/Adnc.Demo.Cust.Api/Adnc.Demo.Cust.Api.csproj”时出错: Invalid value for Link property

**Comment by AlphaYu** [comment]
mac 系统我没法测试，可以尝试直接删除，然后再手工添加进来试试。
