### ISSUE TITLE
注册中心和四个微服务启动后突然终止， 报这个异常，这是什么原因造成的

### ISSUE THREAD

**Issue by tianyang1027** [AlphaYu/adnc#88]
![image](https://github.com/AlphaYu/adnc/assets/7963894/b711b671-c808-4b96-a8b5-c4f318c3e321)

**Comment by AlphaYu** [comment]
看控制台报什么错误信息。

**Comment by tianyang1027** [comment]
![image](https://github.com/AlphaYu/adnc/assets/7963894/44194467-c795-4725-9a28-92e8df4f06bd)

**Comment by AlphaYu** [comment]
很明显的mysql连接失败。。cust,ord,whse先不启动试试。

**Comment by tianyang1027** [comment]
好的，多谢
